#!/bin/bash
echo "============================================================"
echo "  📋 RESUMO - CRÉDITOS TESTNET"
echo "============================================================"
echo ""
echo "✅ ENDEREÇOS OBTIDOS:"
echo ""
echo "🌐 SOLANA TESTNET:"
echo "   Endereço: 2tNwZa6Lx5dLWKEsVDAUhZkXdB8vqksqo2sssWsJ52Y9"
echo "   Faucet: https://faucet.solana.com/"
echo ""
echo "🌐 BSC TESTNET:"
echo "   Status: Configure AWS KMS primeiro"
echo "   Execute: ./get-kms-addresses.sh"
echo ""
echo "============================================================"
echo "  📊 VERIFICAR SALDOS:"
echo "============================================================"
echo ""
echo "Execute: ./verificar-saldos.sh"
echo ""
echo "============================================================"
echo "  📚 DOCUMENTAÇÃO:"
echo "============================================================"
echo ""
echo "• Guia completo: OBTER-TOKENS-TESTNET.md"
echo "• Resumo: RESUMO-CREDITOS-TESTNET.md"
echo ""
